server:
  port: 9000

spring:
  application:
    name: springboot
  datasource:
    url: jdbc:mysql://localhost:3306/house?characterEncoding=UTF-8&useSSL=false&allowMultiQueries=true
    username: root
    password: dandy
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    database: 0
    host: 192.168.206.128
    port: 6379
    password: 123456
    timeout: 1000
    jedis:
      pool:
        max-idle: 10
        max-active: 10
        max-wait: 2000
        min-idle: 5

mybatis:
  #映射文件通配
  mapper-locations: classpath:mapper/*.xml
  #扫描实体类的别名配置,与注解@Alias搭配使用
  type-aliases-package: com.laohu.springboot.mybatistran.pojo
  #typehandler扫描路径
  type-handlers-package: com.laohu.springboot.mybatistran.typehandler
  #mybatis配置文件路径
  #config-location: mybatis/mybatis-config.xml


#日志配置
logging:
  level:
    root: info
    org:
      springframework: info
      org:
        mybatis: debug
